CREATE TABLE Cart (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	creation_date INTEGER NOT NULL DEFAULT (unixepoch() * 1000),
	name TEXT NOT NULL
) STRICT;

CREATE TABLE Item (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	creation_date INTEGER NOT NULL DEFAULT (unixepoch() * 1000),
	cart_id INTEGER NOT NULL,
	section TEXT NOT NULL,
	corridor INTEGER NOT NULL,
	shelf INTEGER NOT NULL,
	subshelf INTEGER,

	photo TEXT NOT NULL,

	FOREIGN KEY (cart_id) REFERENCES Cart (id)
) STRICT;
